project:
  type: website
  output-dir: docs

website:
  title: "Lucia Clarotto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: posts.qmd
        text: Reseach topics
      - href: talks/talks.qmd
        text: Talks
      - about.qmd
      - text: Get in touch!
        menu:
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/in/lucia-clarotto-349022140/
            target: _blank
          - icon: envelope
            text: email
            href: mailto:lucia.clarotto@agroparistech.fr

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual



