project:
  type: website
  output-dir: docs

website:
  title: "Lucia Clarotto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Papers
      - href: posts.qmd
        text: Reseach topics
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual



