project:
  type: website

website:
  title: "Lucia Clarotto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

